### ISSUE TITLE
Textdomain, you are doing it wrong

### ISSUE THREAD

**Issue by collizo4sky** [andrew-worsfold/tailor-woocommerce#1]
You shouldn't be using `tailor()->textdomain()` as textdomain when using l10n / 118n functions.

http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

**Comment by andrew-worsfold** [comment]
Thanks for this!  I had replaced this for a majority of the strings in the plugin, but these got through.  This is now fixed.
